version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: even4-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://neondb_owner:npg_u2A8jOhEfLrF@ep-old-glitter-a86pwjol-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
      - JWT_SECRET=sua_chave_secreta
      - CORS_ORIGIN=http://localhost:3000,http://localhost:8080
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - even4-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/health",
        ]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 30s

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: even4-swagger
    ports:
      - "8080:8080"
    environment:
      - API_URL=http://localhost:3000/api-docs
    depends_on:
      - api
    networks:
      - even4-network

networks:
  even4-network:
    driver: bridge

volumes:
  logs:
