services:
  - type: web
    name: even4-api
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
      - key: PORT
      - key: DATABASE_URL
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
    healthCheckPath: /health 